### ISSUE TITLE
Load existing values in visual mode

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-css#41] opened 2016-09-02 11:55 UTC
This is a fairly challenging enhancement that we've heard requested a few times. Loading a selector in the visual mode should populate all the fields with the current values.

The simplest way to do this would be to look at the attributes of the current selector, but ideally, this should work out the computed values for each selector.

**Comment by braamgenis** [comment] 2017-05-24 10:30
Duplicate of #31

**Closed by braamgenis** 2017-05-24 10:30 UTC
Labels: enhancement, priority-2
