### ISSUE TITLE
CSSLint no longer works

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#48] opened 2016-10-12 15:11 UTC
CSSLinit no longer seems to be working. It likely broke during the recent CSS parser change.

[Slack Reference](https://siteorigin.slack.com/archives/plugins/p1476274272000059)

**Comment by braamgenis** [comment] 2016-10-13 08:04
@AlexGStapleton Just checked in Chrome and Firefox and seems to work for me. Could you maybe give more details like an example with expected and actual behaviours and steps to reproduce?

**Comment by AlexGStapleton** [comment] 2016-10-13 18:43
```
.example#fancy .incorrect < {
   color: #000
   font-weight: 10;
}
```

Should be producing errors (as it's very much wrong) and  warnings, but it doesn't seem to be doing so for me. I'm not able to get them in FireFox or Chrome, on either local or on SiteOrigin.net.

**Comment by braamgenis** [comment] 2016-10-14 08:31
Yeah, that works for me:
![lintin park](https://cloud.githubusercontent.com/assets/3822928/19380759/e1c087fe-91f8-11e6-8176-22a35ffcc8fb.png)

Do you see any JS errors in the console? Which version of the plugin are you using?

**Comment by AlexGStapleton** [comment] 2016-10-14 18:58
1.1.1. 😕

**Comment by gregpriday** [comment] 2016-10-14 19:55
Could be a build config issue.

**Comment by gregpriday** [comment] 2016-11-11 07:50
Turns out this was an issue with Vantage. https://github.com/siteorigin/vantage/commit/c21568d122c84fcab16ae1bbb21018077ac79881

The linting library at the moment conflicts with the WordPress color picker. Causing it to break when it's enqueued. That said, in my testing, it seems like this issue has been fixed, so we can probably remove [this check](https://github.com/siteorigin/so-css/blob/develop/so-css.php#L156).

**Closed by gregpriday** 2016-11-11 07:50 UTC
