### ISSUE TITLE
Expanded Editor: Quotation marks in ::after content are escaped

### ISSUE THREAD

**Issue by Toshiwoz** [siteorigin/so-css#155] opened 2021-11-26 20:30 UTC
I was trying to use the following CSS markup:
```
#home-hero .sow-slider-base::after {
    content: "";
    width: 100%;
    height: 10px;
    background: red;
    position: relative;
    display: table;
}
```

If I add it into the theme CSS directly it works, and even in the editor it works, nonetheless, when I save it, the quotation marks ("), as well as apostrophes (') are escaped, making it into an invalid CSS:

```
#home-hero .sow-slider-base::after {
    content: \"\";
    width: 100%;
    height: 10px;
    background: red;
    position: relative;
    display: table;
}
```

**Comment by Misplon** [comment] 2021-11-26 20:39
Hi, thanks for reaching out.

I've added the above rule here https://demo.siteorigin.com/corp/?ao_noptimize=1. It seems to output as expected:

![Corp_-_A_Modern_Business_Theme_From_SiteOrigin](https://user-images.githubusercontent.com/789159/143628701-61ab3f49-0ae0-45b2-aa14-5576771212c5.jpg)

**Comment by Toshiwoz** [comment] 2021-11-26 20:46
In the editor all looks fine, that little red triangular shape at the end of the header is what I was expecting to see.
![imagen](https://user-images.githubusercontent.com/21297356/143631089-2ade3990-3225-4844-97b4-e8a0aa4c31c9.png)


Nonetheless, when I save it the browser doesn't show it, and inspecting the CSS file I see this `content: \"\";` thingie.
![imagen](https://user-images.githubusercontent.com/21297356/143633116-6f80959f-d231-48b5-bccd-2ea2913958e4.png)

**Comment by Misplon** [comment] 2021-11-26 20:48
Thanks for the screenshots. Please, try checking for a working baseline. Does the issue persist if you temporarily deactivate all plugins except for SiteOrigin CSS and then re-save the contents at Appearance > Custom CSS?

**Comment by Toshiwoz** [comment] 2021-11-26 21:05
Thanks for the suggestion, it is actually a plugin that is causing this:
https://it.wordpress.org/plugins/svg-support/

Fortunately I can get rid of it, although I'd really like to be able to use svg files it's not necessary.
Thanks for your prompt response, by the way.

**Comment by Misplon** [comment] 2021-11-26 21:15
Thanks. SVG Support is present on the Corp demo site. When you have a moment, please, try activating only SiteOrigin CSS and SVG Support. Does the issue persist?

**Comment by Toshiwoz** [comment] 2021-11-26 22:14
![imagen](https://user-images.githubusercontent.com/21297356/143658327-c93312f4-2e9c-4330-a53f-fa1b0ef4e71c.png)
With only the following modules installed I still get the problem, but only if I use the "expand" mode, wher you have the CSS editor on the left, and the preview to the right. If I save from the regular view (no preview), it saves it correctly.

**Comment by Misplon** [comment] 2021-11-27 09:00
Nicely spotted. Thanks for the feedback. I'll ask Alex to attend. The issue won't be resolved in the next release as that's ready to go. I'll ask Alex to send you a beta release once this fix is complete.

**Comment by Toshiwoz** [comment] 2021-11-27 13:32
Cool, thanks. I prefer your tool over the default one.
Since I'm here, it would be cool if there was a way to add a widget with css specific to a page. If I remember correctly, google insight speed doesn't like unused CSS and I don't know of any tool that helps with that.

**Comment by Misplon** [comment] 2021-11-27 14:02
Hi. At the moment, SiteOrigin CSS isn't able to load CSS rules on a per-page basis.

If you want to target rules for specific pages, that can be done using body classes. More on that at the below URL:

https://siteorigin.com/unique-page-styling-custom-css-body-classes/

**Comment by AlexGStapleton** [comment] 2021-11-29 13:43
Hi,

I've come up with a fix for this issue by updating css.js (which is used for processing and parsing CSS). I've [submitted it here](https://github.com/siteorigin/so-css/pull/157) and you've created a build for you to try. You can download it by [clicking here](https://drive.google.com/uc?id=10MBvvFHsnlWLieiWEPrRwpqcoTn6h4oS).

Before proceeding, do a backup.

Navigate to Plugins > Installed Plugins and deactivate SiteOrigin CSS, and then delete it. Scroll to the top of the page and click Add New, Upload Plugin and upload `so-css.1.4.3-beta.zip`. When prompted, activate SiteOrigin CSS. Do the quotation marks still get escaped for you?

Kind regards,
Alex

**Comment by Misplon** [comment] 2021-11-29 20:00
Hi Toshio

Kindly, note that the 1.4.3 release doesn't include the above fix. Please, don't upgrade to 1.4.3 if using the above beta version. The above fix will be included in 1.4.4. or 1.5.

Thanks

Andrew

**Comment by Toshiwoz** [comment] 2021-11-29 20:09
I removed the original plug-in and installed yours, after that I reloaded the css editor page and tried to save in both preview and non preview modes, it still works the same, with the only difference maybe that if I CTRL+F5 in the full editor I do see it escaped even in the editor:
![imagen](https://user-images.githubusercontent.com/21297356/143935712-2c5e73d1-af90-41bf-b04b-1bb556402fbe.png)

**Comment by Misplon** [comment] 2021-11-29 20:13
Thanks. Does the same issue occur if you remove the escaped commas and replace them with `content: "";` and then save?

**Comment by Toshiwoz** [comment] 2021-11-29 20:17
Yes, it happens even if I remove them, unless, as before, I remove them, and save it from the full editor (no preview).

**Comment by Misplon** [comment] 2021-11-29 20:18
Thanks for testing. @AlexGStapleton will follow up when he's next working. Appreciate the help.

**Comment by AlexGStapleton** [comment] 2021-11-30 19:47
Hi Tosh,

I've been unable to replicate this issue after making the changes in https://github.com/siteorigin/so-css/pull/157. 
Would it be possible for you to record a video of this issue occurring for you? I suspect I may be doing something slightly different when replicating and I've ended up fixing the method I found of causing it.

Kind regards,
Alex

**Comment by Toshiwoz** [comment] 2021-12-01 02:22
Sure, no problem.
Tomorrow I'll send a quick clip of the issue.

**Comment by Misplon** [comment] 2021-12-01 08:52
Thanks!

**Comment by Toshiwoz** [comment] 2021-12-01 17:08
https://youtu.be/aYhCogvUWmw
Here we go, it is an unlisted video.

**Comment by Toshiwoz** [comment] 2021-12-03 17:57
Hi, I don't know if it might be realted, but take into account:

- I use firefox developer, in general firefox is a bit strict on certain things.
- I have an adblocker, but I have created an exception for the site, should not be an issue I believe
- The website url is configured locally only, by modifying the hosts file

**Comment by Misplon** [comment] 2021-12-04 09:22
Hi Toshio

Thanks for your detailed feedback. I can replicate the issue. Alex will attend as soon as he's able to.

Chat then.

Cheers, Andrew.

**Comment by AlexGStapleton** [comment] 2021-12-14 13:36
Hi Toshio,

Sorry for the delay. Thanks again for your very detailed feedback! :)

I've identified the cause of the second issue and come up with a fix that's also been added to https://github.com/siteorigin/so-css/pull/157 I've prepared a new build with both changes present and you can download it by [clicking here](https://drive.google.com/uc?id=1bb9Uv2-GiVZaF2CEhYUtVzF7PzUKHAwn).

Before proceeding, do a backup.

Navigate to **Plugins > Installed Plugins** and deactivate SiteOrigin CSS, and then delete it. Scroll to the top of the page and click Add New, Upload Plugin and upload so-css.1.4.3-beta-2.zip. When prompted, activate SiteOrigin CSS. Do the quotation marks still get added after saving?

Please note that this fix isn't able to be retroactive so you'll need to re-save your custom CSS after installing the provided build.

Kind regards,
Alex

**Comment by Toshiwoz** [comment] 2021-12-14 18:45
Yes, it works!
I can save from the preview editor and when refreshing from the regular page I see the changes reflected, and the `content: "";` CSS doesn't escape.

**Comment by AlexGStapleton** [comment] 2021-12-15 15:05
Hi Toshio,

Great to hear that helped! :)
These changes will be included in the new SiteOrigin CSS update.

Kind regards,
Alex

**Closed** 2021-12-15 15:07 UTC
Labels: bug, priority-2
